### ISSUE TITLE
Label issues reported from playground

### ISSUE THREAD

**Issue by emccorson** [OnsenUI/playground#64]
Currently when an issue is reported from https://onsen.io/playground by clicking the 'Report an issue' button, there are no GitHub labels applied to the created issue. It would be better if issues were automatically labelled with the appropriate framework.

One of these labels should be applied:

- `core`
- `react`
- `vue`
- `angular1`
- `angular2+`

These labels already exist in OnsenUI/OnsenUI issues.

The code already uses the framework name and prepends it to the issue title, so it should be straightforward to use that to figure out which label to apply.

The line that needs to be changed is:

https://github.com/OnsenUI/playground/blob/0076812dad8f0cc86b7841bf8223a0e179ef6d1e/js/services.js#L405

**Comment by frandiox** [comment]
@emccorson 	I think it was a permissions issue. Only owners/members of OnsenUI repo can modify labels. Not sure if Github changed its API to support this use case but, at least when this project was created, the labels were ignored even when specified in the URL.

**Comment by emccorson** [comment]
Ah that makes sense. In that case I will close this. Thanks @frandiox !
